# 适配你的 Dockerfile listen=YES
listen=YES
listen_ipv6=NO

# 安全
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022

# 日志
xferlog_enable=YES
xferlog_file=/var/log/vsftpd.log
xferlog_std_format=YES

# 主动模式
connect_from_port_20=YES

# 被动模式
pasv_enable=YES
pasv_min_port=40000
pasv_max_port=40010

# 动态IP
pasv_addr_resolve=NO
pasv_address=0.0.0.0
pasv_promiscuous=YES

# 权限
chroot_local_user=YES
allow_writeable_chroot=YES
pam_service_name=vsftpd
secure_chroot_dir=/usr/share/empty

# 数据目录
local_root=/data
file_open_mode=0666
use_localtime=YES
dirmessage_enable=YES