# 部署参考https://docs.rustfs.com/installation/docker/

services:
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rustfs-data:/data
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  rustfs-data:
    name: rustfs-data