apiVersion: v1
kind: Service
metadata:
  name: superset-nodeport
  namespace: superset
spec:
  type: NodePort
  ports:
  - port: 8088
    targetPort: 8088
      #nodePort: 30088 # 自定义节点端口，范围30000~32767
  selector:
    app: superset # 和原service的标签保持一致，匹配superset pod
