apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-config
data:
  custom.conf: |
    server {
        # POD内默认端口不要改。
        listen 80;
        # 默认监听所有地址，使访问者可通过主机义IP访问，可自定义。
        # server_name _;

        # 健康检查探针，禁止删除，可自定义
        location /healthz {
            access_log off;
            return 200 "OK";
        }
        
        # 留空，可自定义 
        location / {
            add_header Content-Type "text/html; charset=utf-8";
            return 200 "<html><body><h1>Nginx is ready</h1><p>but no app config loaded.</p></body></html>";
        }
    }