
services:
  redis:
  # 镜像说明：https://hub.docker.com/_/redis
    image: redis:8.8.0
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "root123456", "ping"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    command: >
      redis-server
      --bind 0.0.0.0
      --requirepass root123456
      --protected-mode no
      --appendonly yes
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "2.0"
        reservations:
          memory: 512M
          cpus: "0.5"

volumes:
  redis-data:
    name: redis-data