[mysql_connection]
container_name = mysql8-guacamole
db_user = root
db_password = root123456

[database:jnpf_init]
charset = utf8mb4
collate = utf8mb4_unicode_ci

# [database:xxl_job]
# charset = utf8mb4
# collate = utf8mb4_unicode_ci

# [database:jnpf_flow]
# charset = utf8mb4
# collate = utf8mb4_unicode_ci

# [database:jnpf_sso]
# charset = utf8mb4
# collate = utf8mb4_unicode_ci

# [database:jnpf_tenant]
# charset = utf8mb4
# collate = utf8mb4_unicode_ci

# [database:jnpf_init_column]
# charset = utf8mb4
# collate = utf8mb4_unicode_ci