[import_order]
order = jnpf_init,xxl_job,jnpf_flow,jnpf_sso,jnpf_tenant,jnpf_init_column

# SQL文件定义：sql_files:database_name
# 格式：files = file1.sql,file2.sql,...
[sql_files:jnpf_init]
files = jnpf_db_init.sql

[sql_files:xxl_job]
files = jnpf_xxljob_init.sql

[sql_files:jnpf_flow]
files = jnpf_flow_init.sql

[sql_files:jnpf_sso]
files = jnpf_sso_3.5.5.sql,jnpf_sso_3.5.5_data.sql

[sql_files:jnpf_tenant]
files = jnpf_tenant_init.sql

[sql_files:jnpf_init_column]
files = jnpf_db_init.sql