# 创建专用secret
# kubectl create secret generic pg-secret --from-literal=password='你的强密码' -n postgres

# 1. 动态配置文件
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
data:
  postgresql.conf: |
    # 生产环境基础优化
    max_connections = 100
    shared_buffers = 512MB
    effective_cache_size = 1.5GB
    work_mem = 4MB
    maintenance_work_mem = 64MB
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    default_statistics_target = 100

---

# 2. 数据库服务 (Headless Service)
apiVersion: v1
kind: Service
metadata:
  name: postgres-internal
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
  clusterIP: None
---

apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
spec:
  type: NodePort
  selector:
    app: postgres # 必须与 StatefulSet 中的 labels 匹配
  ports:
    - port: 5432         # Service 内部端口
      targetPort: 5432   # 容器内部端口
      # nodePort: 30432    # 外部访问端口 (范围必须在 30000-32767 之间)
      protocol: TCP
---

# 3. 数据库主程序 (StatefulSet)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres-internal"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:18.4
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: password
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        volumeMounts:
        - name: pg-data
          mountPath: /var/lib/postgresql
        - name: config-volume
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
      volumes:
      - name: config-volume
        configMap:
          name: pg-config
  volumeClaimTemplates:
  - metadata:
      name: pg-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi