services:
  mysql9-single:
    image: mysql:9.7.0
    container_name: mysql9-single
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      TZ: Asia/Shanghai
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    secrets:
      - mysql_root_password
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./init-db:/docker-entrypoint-initdb.d:ro
      - mysql9-data:/var/lib/mysql
      - mysql9-log:/var/log/mysql
    ports:
      # 若需仅本机访问改为 "127.0.0.1:3306:3306"
      - "0.0.0.0:3306:3306"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uroot -p\"$(cat /run/secrets/mysql_root_password)\" --silent 2>/dev/null || exit 1",
        ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        # 最大可用
        limits:
          cpus: '2.0'
          memory: 4G
        # 最少保证可用
        reservations:
          cpus: '0.5'
          memory: 1G
    networks:
      - mysql-net

secrets:
  mysql_root_password:
    file: ./.root_password
    
volumes:
  mysql9-data:
    name: mysql9-data
  mysql9-log:
    name: mysql9-log
networks:
  mysql-net:
    name: mysql-net
    driver: bridge