
services:
  mysql9-single:
    image: mysql:9.6.0
    container_name: mysql9-single
    restart: unless-stopped
    healthcheck:
      test: mysql -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD -e "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - "3306:3306"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql9-data:/var/lib/mysql
      - mysql9-log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Shanghai
      LANG: C.UTF-8

volumes:
  mysql9-data:
    name: mysql9-data
  mysql9-log:
    name: mysql9-log