seatunnel:
  engine:
    http:
      enable-http: true
      port: 8080
    history-job-expire-minutes: 1440
    telemetry:
      logs:
        scheduled-deletion-enable: false
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /seatunnel/checkpoint_snapshot
          storage.type: hdfs
          # 若对接HDFS，需配置namenode完整服务名或IP,端口9000
          fs.defaultFS: file://namenode.hadoop.svc.cluster.local:9000