# 自动创建数据卷
volumes:
  metastore-data:
    name: metastore-data
  postgresql-hive-data:
    name: postgresql-hive-data
  postgresql-logs:
    name: postgresql-logs

networks:
  hive:
    name: hive-net
    driver: bridge

services:
  postgresql-hive:
    image: postgres:18.1
    container_name: postgresql-hive
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore_db
      TZ: Asia/Shanghai
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgresql-hive-data:/var/lib/postgresql
      - /etc/localtime:/etc/localtime:ro
      - postgresql-logs:/var/lib/postgresql/18/main/logs
    mem_limit: 4g
    cpus: 2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d metastore_db -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    command: >
      -c max_connections=1000
      -c shared_buffers=1GB
      -c work_mem=32MB
      -c maintenance_work_mem=256MB
      -c effective_cache_size=3GB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c log_min_messages=warning
      -c log_rotation_size=100MB
      -c listen_addresses='*'
    networks:
      - hive

  # Hive Metastore 服务
  metastore:
    image: zhuyifeiruichuang/hive:3.1.2-pg18
    container_name: metastore
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/bin/bash", "-c", "ps -ef | grep HiveMetaStore | grep -v grep"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 80s
    ports:
      - "9083:9083"
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: >
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgresql-hive:5432/metastore_db
        -Djavax.jdo.option.ConnectionUserName=hive
        -Djavax.jdo.option.ConnectionPassword=hive
      # 让hive组件读取该目录下所有配置文件。
      # HIVE_CUSTOM_CONF_DIR:/hive_custom_conf
    volumes:
      - metastore-data:/opt/hive/data/warehouse
      # 将本地的conf目录挂载到容器中，本地目录必须有所有的完整的hive的配置。
      # - ./conf:/hive_custom_conf
    depends_on:
      postgresql-hive:
        condition: service_healthy
    networks:
      - hive

  # Hive Server2 服务
  hiveserver2:
    image: zhuyifeiruichuang/hive:3.1.2-pg18
    container_name: hiveserver2
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/bin/bash", "-c", "ps -ef | grep HiveServer2 | grep -v grep"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 80s
    ports:
      - "10000:10000"
      - "10002:10002"
    environment:
      SERVICE_NAME: hiveserver2
      SERVICE_OPTS: "-Dhive.metastore.uris=thrift://metastore:9083"
      # HIVE_CUSTOM_CONF_DIR:/hive_custom_conf
      IS_RESUME: "true"
    volumes:
      - metastore-data:/opt/hive/data/warehouse
      # - ./conf:/hive_custom_conf
    depends_on:
      metastore:
        condition: service_healthy
    networks:
      - hive