apiVersion: v1
kind: ServiceAccount
metadata:
  name: hadoop
  labels:
    app: hadoop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hadoop
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hadoop
subjects:
  - kind: ServiceAccount
    name: hadoop
    namespace: default
roleRef:
  kind: Role
  name: hadoop
  apiGroup: rbac.authorization.k8s.io