
networks:
  guacamole:
    driver: bridge
    name: guacamole-net

volumes:
  mysql-data:
    name: mysql-data-guacamole
  mysql-log:
    name: mysql-log-guacamole

services:
  # 组件1：Guacd 服务
  guacd:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/guacamole/guacd:1.6.0
    container_name: guacd
    hostname: guacd
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    # ports:
      # - "4822:4822"
    networks:
      - guacamole
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 4822"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # 组件2：MySQL 8 服务
  mysql:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/mysql:8.4.10
    container_name: mysql8-guacamole
    hostname: mysql8-guacamole
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123456"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    # ports:
      # - "3306:3306"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql-data:/var/lib/mysql
      - mysql-log:/var/log/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Shanghai
      LANG: C.UTF-8
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_root
      MYSQL_PASSWORD: guacamole_dbpass#1A
    networks:
      - guacamole

  # 组件3：Guacamole Web 服务
  guacamole:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/guacamole/guacamole:1.6.0
    container_name: guacamole
    hostname: guacamole
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      guacd:
        condition: service_started
    environment:
      TZ: Asia/Shanghai
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      MYSQL_ENABLED: "true"
      MYSQL_HOSTNAME: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_root
      MYSQL_PASSWORD: guacamole_dbpass#1A
      # 指定URL后缀为根目录。可指定为aaa，使访问变为IP:8080/aaa 。若注释掉，需访问IP:8080/guacamole
      WEBAPP_CONTEXT: ROOT
    networks:
      - guacamole
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:8080/ || exit 1"]
      interval: 10s
      timeout: 8s
      retries: 3
      start_period: 30s