#!/bin/bash
set -eo pipefail

# ====================== 核心配置（纯系统自带）======================
JVM_DIR="/usr/lib/jvm"
ENV_FILE="/etc/profile.d/jdk.sh"

# 颜色定义
if [ -t 1 ]; then
    RED='\033[31m'
    GREEN='\033[32m'
    YELLOW='\033[33m'
    BLUE='\033[34m'
    NC='\033[0m'
else
    RED='' GREEN='' YELLOW='' BLUE='' NC=''
fi

# ====================== 核心函数（纯系统自带命令）======================
check_permission() {
    if [ $EUID -ne 0 ]; then
        echo -e "${RED}❌ 错误：请使用root权限运行（sudo bash $0）${NC}"
        exit 1
    fi
}

# 增强：提取安装包的核心版本号（如21、8、17）
extract_package_version() {
    # 从包名提取数字（取最大的核心版本号）
    local pkg_name=$1
    # 仅用/bin/grep + /bin/sort（系统必带）
    PACKAGE_CORE_VERSION=$(/bin/echo "${pkg_name}" | /bin/grep -Eo '[0-9]{1,2}' | /bin/sort -nr | /bin/head -1)
    echo -e "${BLUE}🔍 识别安装包核心版本号：${PACKAGE_CORE_VERSION}${NC}"
}

find_jdk_package() {
    echo -e "\n${BLUE}🔍 查找当前目录的JDK安装包...${NC}"
    JDK_PACKAGES=($(/bin/ls -1 ./ 2>/dev/null | /bin/grep -i 'jdk' | /bin/grep -iE '\.tar\.gz|\.tgz'))
    
    if [ ${#JDK_PACKAGES[@]} -eq 0 ]; then
        echo -e "${RED}❌ 错误：当前目录无JDK tar.gz/tgz包！${NC}"
        exit 1
    elif [ ${#JDK_PACKAGES[@]} -gt 1 ]; then
        echo -e "${YELLOW}⚠️  找到多个JDK包，请选择：${NC}"
        for i in "${!JDK_PACKAGES[@]}"; do
            echo "  $((i+1)). ${JDK_PACKAGES[$i]}"
        done
        read -p "输入序号（1-${#JDK_PACKAGES[@]}）：" SELECT_NUM
        if [ -z "${SELECT_NUM}" ] || [ "${SELECT_NUM}" -lt 1 ] || [ "${SELECT_NUM}" -gt ${#JDK_PACKAGES[@]} ]; then
            echo -e "${RED}❌ 错误：序号非法！${NC}"
            exit 1
        fi
        SELECTED_PACKAGE=${JDK_PACKAGES[$((SELECT_NUM-1))]}
    else
        SELECTED_PACKAGE=${JDK_PACKAGES[0]}
    fi
    # 提取包的核心版本号
    extract_package_version "${SELECTED_PACKAGE}"
    echo -e "${GREEN}✅ 选中安装包：${SELECTED_PACKAGE}${NC}"
}

# 增强：彻底清理所有旧JDK目录（无论目录名）
clean_old_config() {
    echo -e "\n${BLUE}🧹 彻底清理所有旧JDK目录...${NC}"
    # 删除JVM_DIR下所有子目录（保留JVM_DIR本身）
    if [ -d "${JVM_DIR}" ]; then
        /bin/rm -rf "${JVM_DIR}"/* 2>/dev/null
        echo -e "${YELLOW}⚠️  已删除${JVM_DIR}下所有旧目录${NC}"
    fi
    # 清理旧环境变量文件
    /bin/rm -f "${ENV_FILE}" 2>/dev/null
    # 清空命令缓存
    hash -r 2>/dev/null
    echo -e "${GREEN}✅ 旧配置清理完成${NC}"
}

extract_jdk() {
    echo -e "\n${BLUE}📦 解压JDK安装包...${NC}"
    /bin/mkdir -p "${JVM_DIR}" || { echo -e "${RED}❌ 创建${JVM_DIR}失败！${NC}"; exit 1; }

    if ! /bin/tar -zxf "./${SELECTED_PACKAGE}" -C "${JVM_DIR}/"; then
        echo -e "${RED}❌ 解压${SELECTED_PACKAGE}失败！${NC}"
        exit 1
    fi

    # 列出解压后的目录（便于调试）
    echo -e "\n${BLUE}🔍 解压后${JVM_DIR}下的目录：${NC}"
    /bin/ls -1 "${JVM_DIR}"

    # 精准定位：找版本与包匹配的JDK目录
    echo -e "\n${BLUE}🔍 定位与版本${PACKAGE_CORE_VERSION}匹配的JDK目录...${NC}"
    JDK_HOME=""
    for dir in "${JVM_DIR}"/*/; do
        if [ -f "${dir}/bin/java" ]; then
            # 检查目录的Java版本是否含核心版本号
            if "${dir}/bin/java" -version 2>&1 | /bin/grep -q "${PACKAGE_CORE_VERSION}"; then
                JDK_HOME="${dir%/}"
                echo -e "${GREEN}✅ 匹配到目标JDK目录：${JDK_HOME}${NC}"
                break
            fi
        fi
    done

    # 兜底：若未匹配到，取第一个有效JDK目录（防止版本号匹配失败）
    if [ -z "${JDK_HOME}" ]; then
        echo -e "${YELLOW}⚠️  未匹配到版本${PACKAGE_CORE_VERSION}的目录，取第一个有效JDK目录${NC}"
        for dir in "${JVM_DIR}"/*/; do
            if [ -f "${dir}/bin/java" ]; then
                JDK_HOME="${dir%/}"
                break
            fi
        done
    fi

    if [ -z "${JDK_HOME}" ]; then
        echo -e "${RED}❌ 未找到有效JDK目录！${NC}"
        exit 1
    fi
    echo -e "${GREEN}✅ JDK解压完成，路径：${JDK_HOME}${NC}"
}

config_env() {
    echo -e "\n${BLUE}⚙️  配置JDK环境变量...${NC}"
    
    if [ -d "${JDK_HOME}/jre" ]; then
        JRE_CONFIG="export JRE_HOME=\${JAVA_HOME}/jre
export CLASSPATH=.:\${JAVA_HOME}/lib:\${JRE_HOME}/lib"
    else
        JRE_CONFIG="export CLASSPATH=.:\${JAVA_HOME}/lib"
    fi

    /bin/cat > "${ENV_FILE}" << EOF
#!/bin/bash
# Auto generated by JDK install script (offline)
export JAVA_HOME=${JDK_HOME}
${JRE_CONFIG}
export PATH=\${JAVA_HOME}/bin:\${PATH:-}
EOF

    /bin/chmod +x "${ENV_FILE}"
    # 验证环境变量文件内容
    echo -e "\n${BLUE}🔍 环境变量文件内容：${NC}"
    /bin/cat "${ENV_FILE}"
    
    source "${ENV_FILE}" || echo -e "${YELLOW}⚠️  临时生效失败，手动执行：source ${ENV_FILE}${NC}"
    echo -e "${GREEN}✅ 环境变量已写入${ENV_FILE}${NC}"
}

set_default_jdk() {
    echo -e "\n${BLUE}🔧 设置系统默认JDK...${NC}"
    if [ -x "/usr/sbin/update-alternatives" ]; then
        /usr/sbin/update-alternatives --install /usr/bin/java java "${JDK_HOME}/bin/java" 9999 2>/dev/null
        /usr/sbin/update-alternatives --install /usr/bin/javac javac "${JDK_HOME}/bin/javac" 9999 2>/dev/null
        /usr/sbin/update-alternatives --set java "${JDK_HOME}/bin/java" 2>/dev/null
        /usr/sbin/update-alternatives --set javac "${JDK_HOME}/bin/javac" 2>/dev/null
    fi
    if [ -x "/usr/sbin/alternatives" ]; then
        /usr/sbin/alternatives --install /usr/bin/java java "${JDK_HOME}/bin/java" 9999 2>/dev/null
        /usr/sbin/alternatives --install /usr/bin/javac javac "${JDK_HOME}/bin/javac" 9999 2>/dev/null
        /usr/sbin/alternatives --set java "${JDK_HOME}/bin/java" 2>/dev/null
        /usr/sbin/alternatives --set javac "${JDK_HOME}/bin/javac" 2>/dev/null
    fi
    hash -r
    echo -e "${GREEN}✅ 系统默认JDK设置完成${NC}"
}

verify_install() {
    echo -e "\n${BLUE}✅ 验证JDK安装结果...${NC}"
    unset JAVA_HOME PATH
    hash -r
    source "${ENV_FILE}"

    if ! command -v java &>/dev/null; then
        echo -e "${RED}❌ 验证失败：未找到java命令！${NC}"
        exit 1
    fi

    echo -e "${GREEN}======================================================${NC}"
    echo -e "${GREEN}🎉 JDK安装/更新成功！${NC}"
    echo -e "${GREEN}📌 JAVA_HOME：${JAVA_HOME}${NC}"
    echo -e "${GREEN}📌 JDK版本信息：${NC}"
    java -version 2>&1
    echo -e "${GREEN}======================================================${NC}"

    echo -e "\n${YELLOW}💡 环境变量生效说明：${NC}"
    echo -e "${YELLOW}   1. 立即生效：当前终端已自动生效${NC}"
    echo -e "${YELLOW}   2. 永久生效：新终端/重启后自动加载${NC}"
    echo -e "${YELLOW}   3. 手动生效：source ${ENV_FILE}${NC}"
}

# ====================== 主流程 ======================
main() {
    clear
    echo -e "${BLUE}===================== 离线JDK安装脚本 ======================${NC}"
    echo -e "${BLUE}📌 纯系统自带命令 | 彻底清理旧目录 | 精准匹配版本${NC}"
    echo -e "${BLUE}=============================================================${NC}"

    check_permission
    find_jdk_package
    clean_old_config
    extract_jdk
    config_env
    set_default_jdk
    verify_install

    echo -e "\n${GREEN}✅ 所有操作完成！${NC}"
    exit 0
}

main
