# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- namespace/namespace.yaml
- crd/bases/hadoop.apache.org_hadoopclusters.yaml
- rbac/service_account.yaml
- rbac/role.yaml
- rbac/role_binding.yaml
- rbac/leader_election_role.yaml
- rbac/leader_election_role_binding.yaml
- manager/manager.yaml
