apiVersion: v2
name: domino
description: A Helm chart for Domino workflow orchestration platform
type: application
version: 0.2.0
appVersion: "0.1.11"
home: https://github.com/Tauffer-Consulting/domino
sources:
  - https://github.com/Tauffer-Consulting/domino

dependencies:
  - name: airflow
    version: 1.11.0
    repository: https://airflow.apache.org
    condition: airflow.enabled
