services:
  alist:
    image: ghcr.io/alistgo/alist:v3.61.0
    container_name: alist
    volumes:
      - 'alist_data:/opt/alist/data'
    ports:
      - '5244:5244'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    restart: unless-stopped
volumes:
  alist_data:
    name: alist_data